### ISSUE TITLE
Introduce a global flag for pretty json

### ISSUE THREAD

**Issue by lfgcampos** [lfgcampos/axon-server-cli#15]
In [axonserver-cli](https://github.com/AxonIQ/axon-server-se/tree/master/axonserver-cli), we have a flag called `json` for it.

ex: `JSON, err := json.MarshalIndent(input, "", "  ")`

The JSON input (or output) would be:
```
$ ./axon-server-cli.exe application register -a myapp -d "My app from go cli" -r USE_CONTEXT@default
Using config file: C:\Users\Domin\IdeaProjects\axon-server-cli\axonserver-cli.yaml
2020/06/22 14:59:47 calling: http://localhost:8024/v1/applications
applicationJson:
{
  "name": "myapp",
  "description": "My app from go cli",
  "roles": [
    {
      "context": "default",
      "roles": [
        "USE_CONTEXT"
      ]
    }
  ]
}

```

**Comment by lfgcampos** [comment]
I already added a first step to this ticket, a flag called `json`.
As you can see, it should work like this:

```
axon-server-cli version
{"Version":"dev","Commit":"none","Date":"unknown"}
```

```
axon-server-cli version --json
{
  "Version": "dev",
  "Commit": "none",
  "Date": "unknown"
}
```

**Comment by noblica** [comment]
Maybe we can just call it `pretty`, or something else? I mean we're already printing a JSON, just prettier.

**Comment by lfgcampos** [comment]
Agreed to use `pretty-json` as a flag.
