### ISSUE TITLE
Introduce a verbose flag

### ISSUE THREAD

**Issue by lfgcampos** [lfgcampos/axon-server-cli#28]
For all operations we print things related to config, to the command, URLs, etc.
We should only print all that when the verbose flag is active.

**Comment by noblica** [comment]
Good idea. We don't want to over saturate the output with data. Maybe we can just print out some notifications if the verbose flag is inactive, like `created a user with username xxx`, and something similar for other commands?

**Comment by lfgcampos** [comment]
Sounds good, let's keep it as simple as possible when the flag is not activated and way more 'debug feeling' when the flag is on.
